#  servlet:
#    contextPath: /EsenzioniServices
# ===============================
# = DATA SOURCE
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
# ===============================
# = JPA / HIBERNATE
# ===============================
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.DB2Dialect 
    open-in-view: false
  batch:
    job:
      enabled: false
      initialize-schema: never
  main:
    allow-bean-definition-overriding: true

